pool:
  vmImage: 'ubuntu-16.04'

steps:
  - bash: sudo apt-get install azure-functions-core-tools
    displayName: 'sudo apt-get install azure-functions-core-tools'

  - bash: func extensions install
    displayName: 'func extensions install'

  - script: npm install
    displayName: 'npm install'

  - task: ArchiveFiles@2
    displayName: 'Archive Function App'
    inputs:
      archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
      includeRootFolder: false
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      artifactName: 'drop'
      pathtoPublish: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
